import 'package:flutter/material.dart';

class Tour {
  final int index;
  final Widget body;

  Tour(this.index, this.body);
}

class TourPage extends StatelessWidget {
  final String imageUrl;
  final String text;

  TourPage({this.imageUrl, this.text});

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image.asset(
              imageUrl,
              fit: BoxFit.cover,
              width: MediaQuery.of(context).size.width * 0.8,
            ),
            Container(
              padding: EdgeInsets.symmetric(horizontal: 32.0, vertical: 16.0),
              child: Text(
                text,
                style: Theme.of(context).textTheme.subtitle1,
                textAlign: TextAlign.justify,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class TourScreen extends StatefulWidget {
  @override
  _TourScreenState createState() => _TourScreenState();
}

class _TourScreenState extends State<TourScreen>
    with SingleTickerProviderStateMixin {
  TabController _tabCtrl;
  List<Tour> _pages = <Tour>[
    Tour(
      0,
      TourPage(
        imageUrl: 'assets/images/tour1.png',
        text: '2020 is a tough year to human due to COVID-19',
      ),
    ),
    Tour(
      1,
      TourPage(
        imageUrl: 'assets/images/tour2.png',
        text:
            'But it create a positive impact to nature and earth due to lockdown that reduce human activity',
      ),
    ),
    Tour(
      2,
      TourPage(
        imageUrl: 'assets/images/tour3.png',
        text:
            'Many country reported that the air turn fresh, water turn clear, even animals are free!',
      ),
    ),
    Tour(
      3,
      TourPage(
        imageUrl: 'assets/images/tour4.png',
        text:
            'There are also damages we missed seeing, the increase of wastes generated by ecommerce, food delivery services',
      ),
    ),
    Tour(
      4,
      TourPage(
        imageUrl: 'assets/images/tour5.png',
        text:
            'The waste creation like flyer bag, single use food container, carton box increasing tremendously and most of the people didn\'t dispose them correctly',
      ),
    ),
    Tour(
      5,
      TourPage(
        imageUrl: 'assets/images/tour6.png',
        text:
            'Greenery is a community driven platform to promote reduce waste by extend the unwanted lifetime. People can trade or barter the reusable like flyer bag, carton box, bubble wrap',
      ),
    ),
    Tour(
      6,
      TourPage(
        imageUrl: 'assets/images/tour7.png',
        text:
            'With social knowledge, people who are curious, interested or trying to reduce the amount of waste can share their solution and vote for the best',
      ),
    ),
    Tour(
      7,
      TourPage(
        imageUrl: 'assets/images/tour8.png',
        text:
            'Share with who you care and earn the "Green" credit. Together we create a better environment for us and children',
      ),
    ),
  ];

  @override
  void initState() {
    _tabCtrl = TabController(vsync: this, length: _pages.length);
    super.initState();
  }

  @override
  void dispose() {
    _tabCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: null,
      body: Stack(
        children: <Widget>[
          Align(
            alignment: Alignment.bottomCenter,
            child: Container(
              padding: EdgeInsets.symmetric(vertical: 16.0),
              child: TabPageSelector(controller: _tabCtrl),
            ),
          ),
          TabBarView(
            controller: _tabCtrl,
            children: _pages.map((page) {
              return page.body;
            }).toList(),
          ),
          Align(
            alignment: Alignment.bottomRight,
            child: GestureDetector(
              child: Container(
                padding: EdgeInsets.symmetric(horizontal: 32.0, vertical: 16.0),
                child: Text('Close'),
              ),
              onTap: () {
                if (Navigator.of(context).canPop()) {
                  Navigator.of(context).pop();
                } else {
                  Navigator.of(context).pushReplacementNamed('/home');
                }
              },
            ),
          ),
        ],
      ),
    );
  }
}
